version: "3"

services:
    app:
        build: .
        container_name: my-heatmap
        # restart: unless-stopped
        env_file: .env
        volumes:
            - .:/app
            - /app/node_modules # Prevent node_modules from being overwritten
        environment:
            - NODE_ENV=development
        #     - PG_HOST=192.168.1.88
        #     - PG_USER=postgres
        #     - PG_PASSWORD=password
        #     - PG_DATABASE=MyHeatmap
        #     - PG_PORT=8087
        ports:
            - "8085:8085"
        depends_on:
            - db
    db:
        image: postgres:16
        container_name: my-heatmap-db
        restart: unless-stopped
        ports:
            - "8087:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: MyHeatmap
        volumes:
            - ./data/postgres_data:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d
